
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jul 30 12:44:02 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 14;
  public static final int LOGAND = 31;
  public static final int MULT = 22;
  public static final int CONST = 6;
  public static final int NOTEQUAL = 26;
  public static final int LPAREN = 37;
  public static final int GREATER = 27;
  public static final int SEMI = 33;
  public static final int CONTINUE = 13;
  public static final int DECR = 21;
  public static final int LESS = 29;
  public static final int MINUS = 20;
  public static final int CHARACTER = 46;
  public static final int RPAREN = 38;
  public static final int LESSEQUAL = 30;
  public static final int BOOL = 45;
  public static final int COMMA = 35;
  public static final int INC = 18;
  public static final int DIV = 23;
  public static final int PLUS = 17;
  public static final int ASSIGN = 19;
  public static final int IF = 11;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int EQUAL = 25;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int NUMBER = 44;
  public static final int MOD = 24;
  public static final int LSQBRACKET = 42;
  public static final int IDENT = 43;
  public static final int BREAK = 10;
  public static final int VOID = 5;
  public static final int GREATEREQUAL = 28;
  public static final int COLON = 34;
  public static final int UNION = 9;
  public static final int LBRACE = 39;
  public static final int ELSE = 12;
  public static final int READ = 8;
  public static final int WHILE = 16;
  public static final int LOGOR = 32;
  public static final int RBRACE = 40;
  public static final int PROG = 2;
  public static final int RSQBRACKET = 41;
  public static final int PRINT = 3;
  public static final int DO = 15;
}

