
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 10 16:37:22 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 52;
  public static final int LOGAND = 29;
  public static final int MULT = 20;
  public static final int CONST = 6;
  public static final int CASE = 47;
  public static final int NOTEQUAL = 24;
  public static final int LPAREN = 35;
  public static final int GREATER = 25;
  public static final int SEMI = 31;
  public static final int CONTINUE = 12;
  public static final int DECR = 19;
  public static final int FOR = 45;
  public static final int LESS = 27;
  public static final int MINUS = 18;
  public static final int CHARACTER = 44;
  public static final int RPAREN = 36;
  public static final int LESSEQUAL = 28;
  public static final int BOOL = 43;
  public static final int COMMA = 33;
  public static final int INC = 16;
  public static final int DIV = 21;
  public static final int PLUS = 15;
  public static final int ASSIGN = 17;
  public static final int IF = 10;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int EQUAL = 23;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int NUMBER = 42;
  public static final int MOD = 22;
  public static final int LSQBRACKET = 40;
  public static final int IDENT = 41;
  public static final int BREAK = 9;
  public static final int VOID = 5;
  public static final int SWITCH = 46;
  public static final int GREATEREQUAL = 26;
  public static final int COLON = 32;
  public static final int UNION = 51;
  public static final int LBRACE = 37;
  public static final int ELSE = 11;
  public static final int ENUM = 50;
  public static final int READ = 8;
  public static final int WHILE = 14;
  public static final int LOGOR = 30;
  public static final int RBRACE = 38;
  public static final int PROG = 2;
  public static final int RSQBRACKET = 39;
  public static final int QUESTION = 49;
  public static final int LENGTH = 48;
  public static final int PRINT = 3;
  public static final int DO = 13;
}

