package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:

	boolean errorDetected;

	Logger log = Logger.getLogger(getClass());
   
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }


:}

init with {:
	errorDetected = false;
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null)
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROG, PRINT, RETURN, VOID, CONST, NEW, READ, UNION, BREAK, IF, ELSE, CONTINUE, MAP, DO, WHILE;
terminal PLUS, INC, ASSIGN, MINUS, DECR, MULT, DIV, MOD;
terminal EQUAL, NOTEQUAL, GREATER, GREATEREQUAL, LESS, LESSEQUAL, LOGAND, LOGOR;
terminal SEMI, COLON, COMMA, DOT, LPAREN, RPAREN, LBRACE, RBRACE, RSQBRACKET, LSQBRACKET;
terminal String IDENT;
terminal Integer NUMBER, BOOL;
terminal Character CHARACTER;

nonterminal Program, ConstVarDeclList, MethodDeclList, ConstDeclList, VarDeclList, Type;
nonterminal ConstDecl, ConstDeclMore, Constant, VarDecl, VarDeclMore;
nonterminal MethodSignature, MethodSignatureType, FormParsList, FormParsMore, MethodDecl;
nonterminal Statement, StatementList, DesignatorStatement, Condition;
nonterminal StatementReturnExpr, StatementPrintNumConst, StatementIfElse;
nonterminal StatementDoWhileCond, StatementDoWhileCondDesignatorSt;
nonterminal DesignatorStatementFirstOptions, ActPars, ActParsList, ActParsMore;
nonterminal CondTerm, CondTermMore, CondFact, CondFactMore, TermList, SimpleDesignator;
nonterminal MethodDeclVarDeclList, FormPars;
nonterminal Label, Assignop, Relop, Addop, Mulop, Setop;
nonterminal ProgramName, MethodRetAndName;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Factor, FactorMore, Term, ExprAddopTerms, Expr, FactorActPars;
nonterminal	rs.etf.pp1.symboltable.concepts.Obj Designator, DesignatorArrayName;

precedence left ELSE;


Program ::= (Program) PROG ProgramName ConstVarDeclList LBRACE MethodDeclList RBRACE;

ProgramName ::= (ProgramName) IDENT;

ConstVarDeclList ::= (ConstVarDeclList_Const) ConstVarDeclList ConstDeclList
					 |
					 (ConstVarDeclList_Var) ConstVarDeclList VarDeclList
					 | 
					 (ConstVarDeclList_Epsilon) /*epsilon*/
					 ;

ConstDeclList ::= (ConstDeclList) CONST Type ConstDecl ConstDeclMore SEMI;

ConstDecl ::= (ConstDecl) IDENT ASSIGN Constant;

ConstDeclMore ::= (ConstDeclMore_Comma) COMMA ConstDecl ConstDeclMore
				  |
				  (ConstDeclMore_Epsilon) /* epsilon */
				  ;

Constant ::= (Constant_Number) NUMBER
			 |
			 (Constant_Character) CHARACTER
			 |
			 (Constant_Bool) BOOL
			 ;

Type ::= (Type) IDENT;

VarDecl ::= (VarDecl_Regular) IDENT
			|
			(VarDecl_Array) IDENT LSQBRACKET RSQBRACKET
			;

VarDeclList ::= (VarDeclList) Type VarDecl VarDeclMore SEMI;
 			 
VarDeclMore ::= (VarDeclMore_Comma) COMMA VarDecl VarDeclMore
				|
				(VarDeclMore_Semi) /* Epsilon */
				;

MethodSignature ::= (MethodSignature) MethodRetAndName LPAREN FormParsList RPAREN;

MethodRetAndName ::= (MethodRetAndName_Type) Type IDENT
					 |
					 (MethodRetAndName_Void) VOID IDENT
					 ;

FormPars ::= (FormPars_Regular) Type IDENT
			 |
			 (FormPars_Array) Type IDENT LSQBRACKET RSQBRACKET
			 ;

FormParsList ::= (FormParsList_Yes) FormPars FormParsMore
				 |
				 (FormParsList_Epsilon) /* Epsilon */
				 ;

FormParsMore ::= (FormParsMore_Comma) COMMA FormPars FormParsMore
				 |
				 (FormParsMore_Epsilon) /* Epsilon */
				 ;
				 
MethodDecl ::= (MethodDecl) MethodSignature MethodDeclVarDeclList LBRACE StatementList RBRACE;

MethodDeclVarDeclList ::= (MethodDeclVarDeclList_Yes) VarDeclList MethodDeclVarDeclList
						  |
						  (MethodDeclVarDeclList_Epsilon) /* Epsilon */
						  ;

MethodDeclList ::= (MethodDeclList_More) MethodDecl MethodDeclList
				   |
				   (MethodDeclList_Epsilon) /* Epsilon */
				   ;

StatementList ::= (StatementList_More) Statement StatementList
				  |
				  (StatementList_Epsilon) /* Epsilon */
				  ;

Statement ::= (Statement_Designator) DesignatorStatement SEMI
			  |
			  (Statement_If) IF LPAREN Condition RPAREN Statement StatementIfElse
			  |
			  (Statement_Break) BREAK SEMI
			  |
			  (Statement_Continue) CONTINUE SEMI
			  |
			  (Statement_Return) RETURN StatementReturnExpr SEMI
			  |
			  (Statement_Read) READ LPAREN Designator RPAREN SEMI
			  |
			  (Statement_Print) PRINT LPAREN Expr StatementPrintNumConst RPAREN SEMI
			  |
			  (Statement_DoWhile) DO Statement WHILE LPAREN StatementDoWhileCond RPAREN SEMI
			  |
			  (Statement_List) LBRACE StatementList RBRACE
			  ;
			  
StatementIfElse ::= (Statement_IfElse_Yes) ELSE Statement
					 |
					 (Statement_IfElse_Epsilon) /* Epsilon */
					 ;

StatementReturnExpr ::= (Statement_ReturnExpr_Yes) Expr
						 |
						 (Statement_ReturnExpr_Epsilon) /* Epsilon */
						 ;
						 
StatementPrintNumConst ::= (Statement_PrintNumConst_Yes) COMMA NUMBER
							|
							(Statement_PrintNumConst_Epsilon) /* Epsilon */
							;				 
						 
StatementDoWhileCond ::= (Statement_DoWhileCond_Yes) Condition StatementDoWhileCondDesignatorSt
						  |
						  (Statement_DoWhileCond_Epsilon) /* Epsilon */
						  ;
						  
StatementDoWhileCondDesignatorSt ::= (Statement_DoWhileCondDesignatorSt_Yes) COMMA DesignatorStatement
									  |
									  (Statement_DoWhileCondDesignatorSt_Epsilon) /* Epsilon */
									  ;

DesignatorStatement ::= (DesignatorStatement_First) Designator DesignatorStatementFirstOptions
						|
						(DesignatorStatement_Second) Designator Assignop Designator Setop Designator
						;
					 
DesignatorStatementFirstOptions ::= (DesignatorStatement_FirstOptions_Assign) Assignop Expr
							  		 |
							  		 (DesignatorStatement_FirstOptions_ActPars) LPAREN ActParsList RPAREN
							  		 |
							  		 (DesignatorStatement_FirstOptions_Inc) INC
							  		 |
							  		 (DesignatorStatement_FirstOptions_Dec) DECR
							  		 ;

ActPars ::= (ActPars) Expr ActParsMore;

ActParsMore ::= (ActParsMore_Yes) COMMA ActPars
				|
				(ActParsMore_Epsilon) /* Epsilon */
				;
					 
ActParsList ::= (ActParsList_Yes) ActPars
				|
				(ActParsList_Epsilon) /* Epsilon */
			  	;

Condition ::= (Condition) CondTerm CondTermMore;

CondTermMore ::= (CondTermMore_Yes) LOGOR CondTerm CondTermMore
				 |
				 (CondTermMore_Epsilon) /* Epsilon */
				 ;

CondTerm ::= (CondTerm) CondFact CondFactMore;

CondFactMore ::= (CondFactMore_Yes) LOGAND CondFact CondFactMore
				 |
				 (CondFactMore_Epsilon) /* Epsilon */
				 ;

CondFact ::= (CondFact_1) Expr
			 |
			 (CondFact_2) Expr Relop Expr
			 ;

Expr ::= (Expr_Regular) Term ExprAddopTerms
		 |
		 (Expr_Minus) MINUS Term ExprAddopTerms
		 |
		 (Expr_Designator) Designator MAP Designator
		 ;
		 
ExprAddopTerms ::= (ExprAddopTerms_More) Addop Term ExprAddopTerms
				   |
				   (ExprAddopTerms_Epsilon) /* Epsilon */
				   ;
			   		
Term ::= (Term) Factor FactorMore;

FactorMore ::= (FactorMore_Yes) Mulop Factor FactorMore
			   |
			   (FactorMore_Epsilon) /* Epsilon */
			   ;
			   
Factor ::= (Factor_Designator) Designator FactorActPars
		   |
		   (Factor_NumConst) NUMBER
		   |
		   (Factor_CharConst) CHARACTER
		   |
		   (Factor_BoolConst) BOOL
		   |
		   (Factor_New) NEW Type LSQBRACKET Expr RSQBRACKET
		   |
		   (Factor_Expr) LPAREN Expr RPAREN
		   ;
		   
FactorActPars ::= (FactorActPars_Yes) LPAREN ActParsList RPAREN
				  |
				  (FactorActPars_Epsilon) /* Epsilon */
				  ;

Designator ::= (Designator_Regular) IDENT
			   |
			   (Designator_Array) DesignatorArrayName LSQBRACKET Expr RSQBRACKET
			   ;
	   
DesignatorArrayName ::= (DesignatorArrayName) IDENT;
					 
Label ::= (Label) IDENT;

Assignop ::= (Assignop) ASSIGN;

Relop ::= (Relop_Equal) EQUAL
		  |
		  (Relop_Notequal) NOTEQUAL
		  |
		  (Relop_Greater) GREATER
		  |
		  (Relop_Greaterequal) GREATEREQUAL
		  |
		  (Relop_Less) LESS
		  |
		  (Relop_Lessequal) LESSEQUAL
		  ;
		  
Addop ::= (Addop_Plus) PLUS
		  |
		  (Addop_Minus) MINUS
		  ;

Mulop ::= (Mulop_Mult) MULT
		  |
		  (Mulop_Div) DIV
		  |
		  (Mulop_Mod) MOD
		  ;
		  
Setop ::= (Setop) UNION;
					 
					 
					 
					 
					 
					 				 