package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:

	boolean errorDetected;

	Logger log = Logger.getLogger(getClass());
   
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }


:}

init with {:
	errorDetected = false;
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null)
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROG, PRINT, RETURN, VOID, CONST, NEW, READ, BREAK, IF, ELSE, CONTINUE, DO, WHILE;
terminal PLUS, INC, ASSIGN, MINUS, DECR, MULT, DIV, MOD;
terminal EQUAL, NOTEQUAL, GREATER, GREATEREQUAL, LESS, LESSEQUAL, LOGAND, LOGOR;
terminal SEMI, COLON, COMMA, DOT, LPAREN, RPAREN, LBRACE, RBRACE, RSQBRACKET, LSQBRACKET;
terminal String IDENT;
terminal Integer NUMBER, BOOL;
terminal Character CHARACTER;
terminal FOR, SWITCH, CASE, LENGTH, QUESTION, ENUM;
terminal UNION, MAP;

nonterminal Program, ConstVarDeclEnumList, MethodDeclList, ConstDeclList, VarDeclList;
nonterminal ConstDecl, ConstDeclMore, Constant, VarDecl, VarDeclMore;
nonterminal MethodSignature, MethodSignatureType, FormParsList, FormParsMore, MethodDecl;
nonterminal Statement, StatementList, DesignatorStatement;
nonterminal StatementIfElse;
nonterminal StatementDoWhileCond, StatementDoWhileCondDesignatorSt;
nonterminal ActPars, ActParsList, ActParsMore;
nonterminal TermList, SimpleDesignator;
nonterminal MethodDeclVarDeclList, FormPars;
nonterminal Label, Assignop, Relop, Addop, Mulop;
nonterminal ProgramName;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Factor, FactorMore, Term, ExprAddopTerms;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Expr;
nonterminal rs.etf.pp1.symboltable.concepts.Struct FactorActPars, StatementPrintNumConst;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Condition;
nonterminal rs.etf.pp1.symboltable.concepts.Struct CondTerm, CondTermMore, CondFact, CondFactMore;
nonterminal	rs.etf.pp1.symboltable.concepts.Obj Designator, DesignatorName, MethodRetAndName;
nonterminal rs.etf.pp1.symboltable.concepts.Struct StatementReturnExpr;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Type;
nonterminal DoNonterm, ActParsListBegin, Else, WhileNonTerm;

nonterminal EnumBegin, EnumDecl, EnumConst, EnumNumConst, EnumConstMore;
nonterminal SwitchCaseList, SwitchNonTerm, ForCondition, ForNonTerm;
nonterminal	rs.etf.pp1.symboltable.concepts.Obj DesignatorSuffix;
nonterminal rs.etf.pp1.symboltable.concepts.Struct NonTernaryExpr;
nonterminal TernaryColon, SwitchCaseNumber, SwitchCaseColon, SwitchEndStatement;
nonterminal ForDesignatorStatement_1, ForDesignatorStatement_2;


precedence left ELSE;


Program ::= (Program) PROG ProgramName ConstVarDeclEnumList LBRACE MethodDeclList RBRACE;

ProgramName ::= (ProgramName) IDENT;

ConstVarDeclEnumList ::= (ConstVarDeclEnumList_Const) ConstVarDeclEnumList ConstDeclList
						 |
						 (ConstVarDeclEnumList_Var) ConstVarDeclEnumList VarDeclList
						 |
						 (ConstVarDeclEnumList_Enum) ConstVarDeclEnumList EnumDecl
						 |
						 (ConstVarDeclEnumList_Epsilon) /*epsilon*/
						 ;

ConstDeclList ::= (ConstDeclList) CONST Type ConstDecl ConstDeclMore SEMI;

ConstDecl ::= (ConstDecl) IDENT ASSIGN Constant;

ConstDeclMore ::= (ConstDeclMore_Comma) COMMA ConstDecl ConstDeclMore
				  |
				  (ConstDeclMore_Epsilon) /* epsilon */
				  ;

Constant ::= (Constant_Number) NUMBER
			 |
			 (Constant_Character) CHARACTER
			 |
			 (Constant_Bool) BOOL
			 ;

Type ::= (Type) IDENT;

VarDecl ::= (VarDecl_Regular) IDENT
			|
			(VarDecl_Array) IDENT LSQBRACKET RSQBRACKET
			;

VarDeclList ::= (VarDeclList) Type VarDecl VarDeclMore SEMI;
 			 
VarDeclMore ::= (VarDeclMore_Comma) COMMA VarDecl VarDeclMore
				|
				(VarDeclMore_Semi) /* Epsilon */
				;
				
EnumDecl ::= (EnumDecl) ENUM EnumBegin LBRACE EnumConst EnumConstMore RBRACE;

EnumBegin ::= (EnumBegin) IDENT;

EnumConst ::= (EnumConst) IDENT EnumNumConst;
				 
EnumConstMore ::= (EnumConstMore_Yes) COMMA EnumConst EnumConstMore
				  |
				  (EnumConstMore_Epsilon) /* Epsilon */
				  ;

EnumNumConst ::= (EnumNumConst_Yes) ASSIGN NUMBER
				 |
				 (EnumNumConst_Epsilon) /* Epsilon */
				 ;

MethodSignature ::= (MethodSignature) MethodRetAndName LPAREN FormParsList RPAREN;

MethodRetAndName ::= (MethodRetAndName_Type) Type IDENT
					 |
					 (MethodRetAndName_Void) VOID IDENT
					 ;

FormPars ::= (FormPars_Regular) Type IDENT
			 |
			 (FormPars_Array) Type IDENT LSQBRACKET RSQBRACKET
			 ;

FormParsList ::= (FormParsList_Yes) FormPars FormParsMore
				 |
				 (FormParsList_Epsilon) /* Epsilon */
				 ;

FormParsMore ::= (FormParsMore_Comma) COMMA FormPars FormParsMore
				 |
				 (FormParsMore_Epsilon) /* Epsilon */
				 ;
				 
MethodDecl ::= (MethodDecl) MethodSignature MethodDeclVarDeclList LBRACE StatementList RBRACE;

MethodDeclVarDeclList ::= (MethodDeclVarDeclList_Yes) VarDeclList MethodDeclVarDeclList
						  |
						  (MethodDeclVarDeclList_Epsilon) /* Epsilon */
						  ;

MethodDeclList ::= (MethodDeclList_More) MethodDecl MethodDeclList
				   |
				   (MethodDeclList_Epsilon) /* Epsilon */
				   ;

StatementList ::= (StatementList_More) Statement StatementList
				  |
				  (StatementList_Epsilon) /* Epsilon */
				  ;

Statement ::= (Statement_Designator) DesignatorStatement SEMI
			  |
			  (Statement_If) IF LPAREN Condition RPAREN Statement StatementIfElse
			  |
			  (Statement_Break) BREAK SEMI
			  |
			  (Statement_Continue) CONTINUE SEMI
			  |
			  (Statement_Return) RETURN StatementReturnExpr SEMI
			  |
			  (Statement_Read) READ LPAREN Designator RPAREN SEMI
			  |
			  (Statement_Print) PRINT LPAREN Expr StatementPrintNumConst RPAREN SEMI
			  |
			  (Statement_DoWhile) DoNonterm Statement WhileNonTerm LPAREN StatementDoWhileCond RPAREN SEMI
			  |
			  (Statement_Switch) SwitchNonTerm LPAREN Expr RPAREN LBRACE SwitchCaseList RBRACE
			  |
			  (Statement_For) ForNonTerm LPAREN ForDesignatorStatement_1 SEMI ForCondition SEMI ForDesignatorStatement_2 RPAREN Statement
			  |
			  (Statement_List) LBRACE StatementList RBRACE
			  ;
			  
SwitchNonTerm ::= (SwitchNonTerm) SWITCH;
			  
SwitchCaseList ::= (SwitchCaseList_More) CASE SwitchCaseNumber SwitchCaseColon StatementList SwitchEndStatement SwitchCaseList
				   |
				   (SwitchCaseList_Epsilon) /* Epsilon */
				   ;
				   
SwitchCaseNumber ::= (SwitchCaseNumber) NUMBER;

SwitchCaseColon ::= (SwitchCaseColon) COLON;

SwitchEndStatement ::= (SwitchEndStatement) /* Epsilon */;
				   
ForDesignatorStatement_1 ::= (ForDesignatorStatement_1_Yes) DesignatorStatement
						     |
						     (ForDesignatorStatement_1_Epsilon) /* Epsilon */
						     ;

ForDesignatorStatement_2 ::= (ForDesignatorStatement_2_Yes) DesignatorStatement
						     |
						     (ForDesignatorStatement_2_Epsilon) /* Epsilon */
						     ;

ForCondition ::= (ForCondition_Yes) Condition
				 |
				 (ForCondition_Epsilon) /* Epsilon */
				 ;
				 
ForNonTerm ::= (ForNonTerm) FOR;

DoNonterm ::= (DoNonterm) DO;

WhileNonTerm ::= (WhileNonTerm) WHILE;
			  
StatementIfElse ::= (Statement_IfElse_Yes) Else Statement
					 |
					 (Statement_IfElse_Epsilon) /* Epsilon */
					 ;

Else ::= (Else) ELSE;

StatementReturnExpr ::= (Statement_ReturnExpr_Yes) Expr
						 |
						 (Statement_ReturnExpr_Epsilon) /* Epsilon */
						 ;
						 
StatementPrintNumConst ::= (Statement_PrintNumConst_Yes) COMMA NUMBER
							|
							(Statement_PrintNumConst_Epsilon) /* Epsilon */
							;				 
						 
StatementDoWhileCond ::= (Statement_DoWhileCond_Yes) Condition StatementDoWhileCondDesignatorSt
						  |
						  (Statement_DoWhileCond_Epsilon) /* Epsilon */
						  ;
						  
StatementDoWhileCondDesignatorSt ::= (Statement_DoWhileCondDesignatorSt_Yes) COMMA DesignatorStatement
									  |
									  (Statement_DoWhileCondDesignatorSt_Epsilon) /* Epsilon */
									  ;

DesignatorStatement ::= (DesignatorStatement_Assign) Designator Assignop Expr
						|
						(DesignatorStatement_ActPars) Designator LPAREN ActParsList RPAREN
						|
						(DesignatorStatement_Inc) Designator INC
						|
						(DesignatorStatement_Dec) Designator DECR
						;		 

ActPars ::= (ActPars) Expr ActParsMore;

ActParsMore ::= (ActParsMore_Yes) COMMA ActPars
				|
				(ActParsMore_Epsilon) /* Epsilon */
				;
					 
ActParsList ::= (ActParsList_Yes) ActParsListBegin ActPars
				|
				(ActParsList_Epsilon) ActParsListBegin /* epsilon */
			  	;
			  	
ActParsListBegin ::= (ActParsListBegin) /* epsilon */;

Condition ::= (Condition) CondTerm CondTermMore;

CondTermMore ::= (CondTermMore_Yes) LOGOR CondTerm CondTermMore
				 |
				 (CondTermMore_Epsilon) /* Epsilon */
				 ;

CondTerm ::= (CondTerm) CondFact CondFactMore;

CondFactMore ::= (CondFactMore_Yes) LOGAND CondFact CondFactMore
				 |
				 (CondFactMore_Epsilon) /* Epsilon */
				 ;

CondFact ::= (CondFact_1) NonTernaryExpr
			 |
			 (CondFact_2) NonTernaryExpr Relop NonTernaryExpr
			 ;

Expr ::= (Expr_NonTernary) NonTernaryExpr
		 |
		 (Expr_Ternary) Condition QUESTION Expr TernaryColon Expr
		 ;
		 
TernaryColon ::= (TernaryColon) COLON;

NonTernaryExpr ::= (NonTernaryExpr_Regular) Term ExprAddopTerms
				   |
				   (NonTernaryExpr_Minus) MINUS Term ExprAddopTerms
				   ;

ExprAddopTerms ::= (ExprAddopTerms_More) Addop Term ExprAddopTerms
				   |
				   (ExprAddopTerms_Epsilon) /* Epsilon */
				   ;
			   		
Term ::= (Term) Factor FactorMore;

FactorMore ::= (FactorMore_Yes) Mulop Factor FactorMore
			   |
			   (FactorMore_Epsilon) /* Epsilon */
			   ;
			   
Factor ::= (Factor_Var) Designator
		   |
		   (Factor_Meth) Designator LPAREN ActParsList RPAREN
		   |
		   (Factor_NumConst) NUMBER
		   |
		   (Factor_CharConst) CHARACTER
		   |
		   (Factor_BoolConst) BOOL
		   |
		   (Factor_New) NEW Type LSQBRACKET Expr RSQBRACKET
		   |
		   (Factor_Expr) LPAREN Expr RPAREN
		   ;

Designator ::= (Designator_Suffix) DesignatorName DesignatorSuffix
			   |
			   (Designator_Regular) IDENT
			   ;

DesignatorSuffix ::= (Designator_Enum) DOT IDENT
                   	 |
                     (Designator_Length) DOT LENGTH
                   	 |
                   	 (Designator_Array) LSQBRACKET Expr RSQBRACKET
                   	 ;
	   
DesignatorName ::= (DesignatorName) IDENT;
					 
Label ::= (Label) IDENT;

Assignop ::= (Assignop) ASSIGN;

Relop ::= (Relop_Equal) EQUAL
		  |
		  (Relop_Notequal) NOTEQUAL
		  |
		  (Relop_Greater) GREATER
		  |
		  (Relop_Greaterequal) GREATEREQUAL
		  |
		  (Relop_Less) LESS
		  |
		  (Relop_Lessequal) LESSEQUAL
		  ;
		  
Addop ::= (Addop_Plus) PLUS
		  |
		  (Addop_Minus) MINUS
		  ;

Mulop ::= (Mulop_Mult) MULT
		  |
		  (Mulop_Div) DIV
		  |
		  (Mulop_Mod) MOD
		  ;
					 
					 
					 
					 
					 
					 				 